version: 0.2

phases:
    install:
        commands:
            # Environment setup
            - sudo apt-get -y update
            - apt-get install -y apt-transport-https ca-certificates
            - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            - sudo apt-get -y update

            # Yarn installation
            - apt-get install -y yarn
            - yarn -v

            # App dependencies
            - yarn install
    build:
        commands:
            - yarn run build
    post_build:
        commands:
            - aws s3 sync --delete ./dist s3://lil.boy.media
            - aws cloudfront create-invalidation --distribution-id E3HIM3DWT8T7O5 --paths '/*'
